// config.js (generated by GitHub Actions)
window.CONFIG = {
  GEMINI_API_KEY: 'your-api-key-here'
};
const API_KEY = process.env.GEMINI_API_KEY
// main.js - Your application code
const API_KEY = window.CONFIG.GEMINI_API_KEY;

async function callGeminiAPI(prompt) {
  try {
    const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': API_KEY
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }]
      })
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Gemini API Error:', error);
    throw error;
  }
}
